### ISSUE TITLE
Reduction of Anys and more types

### ISSUE THREAD

**Issue by OlliePugh** [smyrgeorge/janus-gateway-tsdx#4]
This package has some really weird scenarios where any is used pretty unnecessarily, for example: 

`createSession(): Promise<any> {
    return this.sendSync({ janus: 'create' }, this);
}
`
Can easily be shown as:
`createSession(): Promise<Session> {
    return this.sendSync({ janus: 'create' }, this);
}
`

I am  happy to start putting some PR's forward for this as I have a fork with a few changes already. My only concern is the testing approach for all of this, as of right now there are no tests for this package. How do you feel about changing all of these types with no tests? I also dont mind contributing in unit testing if this package is still to be maintained. My question is essentially are you still accepting contributions for this or is it abandoned? :)

**Comment by smyrgeorge** [comment]
Hello! Thanks for your reply.
Yeah I know about the Anys. When I forked the library from the original JavaScript one I didn't have enough time to finish the migration declare the types.

So any contributions are of course accepted 🙂

Although I still use the library in production for a small private project. Until now works fine 🙂.

Also apart from the Anys I was planning to do several changes but at the end I didn't had enough time.
I wanted to make use of async/await which could make the code cleaner.
Also, I was planning to remove the bluebird (that was originally in the JavaScript project) but after 1-2 tries I gave up.

Just take a look at the TODO list in the Readme file.

Also if you want adicional help fill free to send me. I will be available.

**Comment by OlliePugh** [comment]
Okay cool, I have raised a branch on my fork that I will start making my changes to and will raise a PR when its ready https://github.com/smyrgeorge/janus-gateway-tsdx/pull/5

What sort of testing do you want to do? I would say maybe integration testing is the best choice for this sort of project over unit? Happy either way but would be good to get some input regarding that 👍

**Comment by smyrgeorge** [comment]
Thanks a lot for your work. 👍👍

I think that integration testing would be a better option for this project.

**Comment by OlliePugh** [comment]
Integration makes sense, is the main target browsers? If so we can use cypress? But cypress feels more focused towards UI's.

Other option is to just run normally with jest and use a nodejs shim, but seems that there aren't any popular actively maintained web rtc libraries that are designed to be ran in NodeJS instead of the browser 🤔
